    title: From 231
    description: Join me every Tuesday for From 231, a fun and easy-going look at everything Whitecaps FC  straight from my seat in... Section 231..
    remote_theme: just-the-docs/just-the-docs
